// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCto9t0dLGIpHpMoi0AECVLEVwRk_DBflE',
    appId: '1:452677055170:web:367312465b3c424627c15b',
    messagingSenderId: '452677055170',
    projectId: 'fluttertask-14ab3',
    authDomain: 'fluttertask-14ab3.firebaseapp.com',
    storageBucket: 'fluttertask-14ab3.appspot.com',
    measurementId: 'G-J8EFT19MEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAbsRaQET88SCFyW3LFJUAiHToewomYms',
    appId: '1:452677055170:android:5a265bab50e54d5427c15b',
    messagingSenderId: '452677055170',
    projectId: 'fluttertask-14ab3',
    storageBucket: 'fluttertask-14ab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUGF7fS9LWg-H12M3V4N6QijZ-RWllUzY',
    appId: '1:452677055170:ios:5832d24e8abede5627c15b',
    messagingSenderId: '452677055170',
    projectId: 'fluttertask-14ab3',
    storageBucket: 'fluttertask-14ab3.appspot.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUGF7fS9LWg-H12M3V4N6QijZ-RWllUzY',
    appId: '1:452677055170:ios:bf566b998e5c86da27c15b',
    messagingSenderId: '452677055170',
    projectId: 'fluttertask-14ab3',
    storageBucket: 'fluttertask-14ab3.appspot.com',
    iosBundleId: 'com.example.flutterTask.RunnerTests',
  );
}
